<?php

namespace WSUWP\Content_Syndicate\WSU_Taxonomies;

add_filter( 'wsuwp_content_syndicate_default_atts', 'WSUWP\Content_Syndicate\WSU_Taxonomies\append_default_attributes' );
add_filter( 'wsuwp_content_syndicate_json_taxonomy_filters', 'WSUWP\Content_Syndicate\WSU_Taxonomies\build_taxonomy_filters', 10, 2 );
add_action( 'rest_query_vars', 'WSUWP\Content_Syndicate\WSU_Taxonomies\rest_query_vars' );
add_filter( 'query_vars', 'WSUWP\Content_Syndicate\WSU_Taxonomies\query_vars' );
add_filter( 'rest_post_query', 'WSUWP\Content_Syndicate\WSU_Taxonomies\rest_post_query', 11 );

/**
 * Append a list of default attributes to account for as part of this
 * taxonomy extension.
 *
 * @param array $atts WSUWP Content Syndicate shortcode attributes.
 *
 * @return array Modified list of default shortcode attributes.
 */
function append_default_attributes( $atts ) {
	$wsu_taxonomy_atts = array(
		'university_category_slug' => '',
		'university_organization_slug' => '',
		'university_location_slug' => '',
		'university_location' => '',
		'university_location_match' => '',
		'taxonomy_match' => '',
		'site_category_slug' => '',
		'category' => '',
		'category_match' => '',
		'tag' => '',
	);

	return $atts + $wsu_taxonomy_atts;
}

/**
 * Build taxonomies on the REST API request URL generated by WSUWP Content Syndicate.
 *
 * @since 0.0.1
 *
 * @param string $request_url
 * @param array  $atts
 *
 * @return string
 */
function build_taxonomy_filters( $request_url, $atts ) {
	$university_category = false;

	if ( ! empty( $atts['university_category'] ) ) {
		$university_category = sanitize_terms( $atts['university_category'] );
	} elseif ( ! empty( $atts['university_category_slug'] ) ) {
		$university_category = sanitize_terms( $atts['university_category_slug'] );
	}

	if ( ! empty( $university_category ) ) {
		$request_url = add_query_arg( array(
			'filter[wsuwp_university_category]' => $university_category,
		), $request_url );
	}

	if ( ! empty( $university_category ) && isset( $atts['university_category_match'] ) && 'all' === $atts['university_category_match'] ) {
		$request_url = add_query_arg( array(
			'filter[wsu_cat_match]' => 'all',
		), $request_url );
	}

	$university_organization = false;

	if ( ! empty( $atts['university_organization'] ) ) {
		$university_organization = sanitize_terms( $atts['university_organization'] );
	} elseif ( ! empty( $atts['university_organization_slug'] ) ) {
		$university_organization = sanitize_terms( $atts['university_organization_slug'] );
	}

	if ( ! empty( $university_organization ) ) {
		$request_url = add_query_arg( array(
			'filter[wsuwp_university_org]' => $university_organization,
		), $request_url );
	}

	if ( ! empty( $university_organization ) && isset( $atts['university_organization_match'] ) && 'all' === $atts['university_organization_match'] ) {
		$request_url = add_query_arg( array(
			'filter[wsu_org_match]' => 'all',
		), $request_url );
	}

	$university_location = false;

	if ( ! empty( $atts['university_location'] ) ) {
		$university_location = sanitize_terms( $atts['university_location'] );
	} elseif ( ! empty( $atts['university_location_slug'] ) ) {
		$university_location = sanitize_terms( $atts['university_location_slug'] );
	}

	if ( ! empty( $university_location ) ) {
		$request_url = add_query_arg( array(
			'filter[wsuwp_university_location]' => $university_location,
		), $request_url );
	}

	if ( ! empty( $university_location ) && isset( $atts['university_location_match'] ) && 'all' === $atts['university_location_match'] ) {
		$request_url = add_query_arg( array(
			'filter[wsu_location_match]' => 'all',
		), $request_url );
	}

	$category = false;

	// Support the older site_category_slug attribute as well as category.
	if ( ! empty( $atts['category'] ) ) {
		$category = sanitize_terms( $atts['category'] );
	} elseif ( ! empty( $atts['site_category_slug'] ) ) {
		$category = sanitize_terms( $atts['site_category_slug'] );
	}

	if ( ! empty( $category ) ) {
		$request_url = add_query_arg( array(
			'filter[category_name]' => $category,
		), $request_url );
	}

	if ( ! empty( $category ) && isset( $atts['category_match'] ) && 'all' === $atts['category_match'] ) {
		$request_url = add_query_arg( array(
			'filter[category_match]' => 'all',
		), $request_url );
	}

	$tag = false;

	if ( ! empty( $atts['tag'] ) ) {
		$tag = sanitize_terms( $atts['tag'] );
	}

	if ( ! empty( $tag ) ) {
		$request_url = add_query_arg( array(
			'filter[tag]' => $tag,
		), $request_url );
	}

	if ( ! empty( $tag ) && isset( $atts['tag_match'] ) && 'all' === $atts['tag_match'] ) {
		$request_url = add_query_arg( array(
			'filter[tag_match]' => 'all',
		), $request_url );
	}

	if ( isset( $atts['taxonomy_match'] ) && 'any' === $atts['taxonomy_match'] ) {
		$request_url = add_query_arg( array(
			'filter[taxonomy_match]' => 'any',
		), $request_url );
	}

	return $request_url;
}

/**
 * Sanitize a list of term slugs so that they can be appended as query
 * variable data in a URL.
 *
 * @since 0.0.1
 *
 * @param string $terms
 *
 * @return string
 */
function sanitize_terms( $terms ) {
	$term_array = explode( ',', $terms );
	$sanitize_term_array = array_map( 'sanitize_key', $term_array );
	$imploded_terms = implode( ',', $sanitize_term_array );
	return $imploded_terms;
}

/**
 * Make the `tax_query` argument available to the REST API request.
 *
 * @since 0.0.1
 *
 * @param array $vars
 *
 * @return array
 */
function rest_query_vars( $vars ) {
	array_push( $vars, 'tax_query' );
	return $vars;
}


/**
 * Filter the query vars that the plugin expects to be available through the
 * the `filter` query argument attached to REST request URLs.
 *
 * @since 0.0.1
 *
 * @param array $vars
 *
 * @return array
 */
function query_vars( $vars ) {
	array_push( $vars, 'category_match' );
	array_push( $vars, 'wsu_cat_match' );
	array_push( $vars, 'wsu_org_match' );
	array_push( $vars, 'wsu_location_match' );
	array_push( $vars, 'tag_match' );
	array_push( $vars, 'taxonomy_match' );

	return $vars;
}


/**
 * Build a taxonomy query from taxonomy terms passed via filter parameters
 * in the REST API request.
 *
 * @since 0.0.1
 *
 * @param array $args
 *
 * @return array
 */
function rest_post_query( $args ) {
	$taxonomies = array(
		'university_category' => array(
			'filter' => 'wsuwp_university_category',
			'taxonomy' => 'wsuwp_university_category',
			'match' => 'wsu_cat_match',
			'query' => array(),
		),
		'university_organization' => array(
			'filter' => 'wsuwp_university_org',
			'taxonomy' => 'wsuwp_university_org',
			'match' => 'wsu_org_match',
			'query' => array(),
		),
		'university_location' => array(
			'filter' => 'wsuwp_university_location',
			'taxonomy' => 'wsuwp_university_location',
			'match' => 'wsu_location_match',
			'query' => array(),
		),
		'category' => array(
			'filter' => 'category_name',
			'taxonomy' => 'category',
			'match' => 'category_match',
			'query' => array(),
		),
		'tag' => array(
			'filter' => 'tag',
			'taxonomy' => 'tag',
			'match' => 'tag_match',
			'query' => array(),
		),
	);

	foreach ( $taxonomies as $key => $taxonomy ) {
		if ( isset( $args[ $taxonomy['filter'] ] ) && ! empty( $args[ $taxonomy['filter'] ] ) ) {
			$terms = explode( ',', $args[ $taxonomy['filter'] ] );

			if ( 2 <= count( $terms ) && isset( $args[ $taxonomy['match'] ] ) && 'all' === $args[ $taxonomy['match'] ] ) {
				$taxonomies[ $key ]['query']['relation'] = 'OR';
			} elseif ( 2 <= count( $terms ) ) {
				$taxonomies[ $key ]['query']['relation'] = 'AND';
			}

			foreach ( $terms as $term ) {
				$taxonomies[ $key ]['query'][] = array(
					'taxonomy' => $taxonomy['taxonomy'],
					'field' => 'slug',
					'terms' => $term,
				);
			}
		}
	}

	$tax_query = array(
		'relation' => 'AND',
	);

	$queries = 0;
	foreach ( $taxonomies as $key => $taxonomy ) {
		unset( $args[ $taxonomy['filter'] ] );

		if ( empty( $taxonomy['query'] ) ) {
			continue;
		}

		$tax_query[] = $taxonomy['query'];
		$queries++;
	}

	if ( isset( $args['taxonomy_match'] ) && 'any' === $args['taxonomy_match'] ) {
		$tax_query['relation'] = 'OR';
	}

	if ( 1 >= $queries ) {
		unset( $tax_query['relation'] );
	}

	if ( ! empty( $tax_query ) ) {
		$args['tax_query'] = $tax_query;
	}

	return $args;
}
